name: PR – Build Check no anda el pr si no buildea

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write  # ← Necesario para comentar en PRs

jobs:
  build:
    name: Build (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20] #mismo job dos veces con diferentes versiones de node

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # descargamos el code

      - name: Setup Node # configuramos la version de node y cacheamos para qeu se aceleren los prox build
        uses: actions/setup-node@v4 # 
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Cache Next build cache # cacheamos la build de next para que sea mas rapido 
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            next-${{ runner.os }}-${{ matrix.node }}-
            next-

      - name: Build # hacemos la build y vemos que todo funcione ok
        env:
          NODE_ENV: production
          NODE_OPTIONS: --max_old_space_size=4096 
        run: npm run build

      #Comentario cuando el build es exitoso para Node 20
      - name: Comment PR Build Success
        if: success() && matrix.node == 20
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**Build exitoso!**\n\n' +
                    '- Compilación exitosa en Node.js 18 y 20\n' +
                    '- Todas las dependencias instaladas correctamente\n' +
                    '- Aplicación lista para producción\n\n' +
                    'Tu código está listo para merge!'
            })
            
      # Comentario cuando el build falla (solo para Node 20)
      - name: Comment PR Build Failure
        if: failure() && matrix.node == 20
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**Build falló!**\n\n' +
                    '**Posibles causas:**\n' +
                    '- Error de sintaxis TypeScript\n' +
                    '- Dependencia faltante o incompatible\n' +
                    '- Error en la configuración de Next.js\n\n' +
                    '[Ver detalles del error](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\n' +
                    '**Tip:** Ejecuta `npm run build` localmente para reproducir el error.'
            })
